# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1a1b26"

# Main text color
theme[main_fg]="#c0caf5"

# Title color for boxes
theme[title]="#7aa2f7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f7768e"

# Background color of selected item in processes box
theme[selected_bg]="#7aa2f7"

# Foreground color of selected item in processes box
theme[selected_fg]="#1a1b26"

# Color of inactive/disabled text
theme[inactive_fg]="#565f89"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#7dcfff"

# Box outline and divider line color
theme[cpu_box]="#565f89"
theme[mem_box]="#565f89"
theme[net_box]="#565f89"
theme[proc_box]="#565f89"
theme[div_line]="#565f89"

# Gradient for all meters and graphs
theme[temp_start]="#9ece6a"
theme[temp_mid]="#e0af68"
theme[temp_end]="#f7768e"


theme[cpu_start]="#9ece6a"
theme[cpu_mid]="#e0af68"
theme[cpu_end]="#f7768e"


theme[free_start]="#9ece6a"
theme[free_mid]="#e0af68"
theme[free_end]="#f7768e"


theme[cached_start]="#bb9af7"
theme[cached_mid]="#bb9af7"
theme[cached_end]="#bb9af7"


theme[available_start]="#7dcfff"
theme[available_mid]="#7dcfff"
theme[available_end]="#7dcfff"


theme[used_start]="#f7768e"
theme[used_mid]="#f7768e"
theme[used_end]="#f7768e"


theme[download_start]="#7dcfff"
theme[download_mid]="#7aa2f7"
theme[download_end]="#bb9af7"


theme[upload_start]="#9ece6a"
theme[upload_mid]="#e0af68"
theme[upload_end]="#f7768e"
